version: '2.1'

services:
  angular-cosmosdb:
    image: johnpapa/angular-cosmosdb:latest
    build: .
    environment:
      TWITTER_CALLBACK_URL: http://localhost:3001/api/auth/twitter/callback
    ports:
      - 3001:3001
      - 9229:9229
    expose:
      - 9229
    command: node --inspect index.js
